version: "3.8"

networks:
  network-rest-api:
    name: network-rest-api
services:
  nginx:
    container_name: nginx
    image: "nginx:stable-alpine"
    ports:
      - "8000:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./src:/var/www/laravel
    networks:
      - network-rest-api
    depends_on:
      - php
      - mysql
  php:
    container_name: php
    build:
      context: dockerfiles
      dockerfile: php.Dockerfile
    volumes:
      - ./src:/var/www/laravel
    depends_on:
      - mysql
    networks:
      - network-rest-api
  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - "3316:3306"
    environment:
      MYSQL_DATABASE: rest-api
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
    - db-data:/var/lib/mysql
    networks:
      - network-rest-api
  composer:
    container_name: composer
    build:
      context: dockerfiles
      dockerfile: composer.Dockerfile
    volumes:
      - ./src:/var/www/laravel
    networks:
      - network-rest-api
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    depends_on:
      - mysql
    ports:
      - 1600:80
    networks:
      - network-rest-api
  artisan:
    networks:
      - network-rest-api
    build:
      context: dockerfiles
      dockerfile: php.Dockerfile
    volumes:
      - ./src:/var/www/laravel
    entrypoint: ["php", "/var/www/laravel/artisan"]

volumes:
  db-data: